version: 2
jobs:
  build:
    working_directory: ~/phovea
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get install -y nodejs npm
            sudo pip install virtualenv
            (!(test -f docker_packages.txt) || (cat docker_packages.txt | xargs sudo apt-get install -y))
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}-{{ checksum "docker_packages.txt" }}
      - run:
          command: |
            virtualenv ~/venv
            . ~/venv/bin/activate
            pip install -r requirements_dev.txt
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}-{{ checksum "docker_packages.txt" }}
          paths:
          - ~/venv
      - run:
          command: |
            . ~/venv/bin/activate
            npm run dist
      - store_artifacts:
          path: dist
          prefix: dist
