version: '2.0'
services:
  api:
    build:
      context: .
      dockerfile: deploy/Dockerfile_dev
    ports:
    - '9000:80'
#    - '2222:22'
#    command: /usr/sbin/sshd -D
    volumes:
    - .:/phovea
