swagger: '2.0'

# This is your document metadata
info:
  version: '0.0.1'
  title: Dataset API

produces:
  - application/json

paths:
  /:
    get:
      operationId: dataset_api.list_dataset
      description: list all datasets
      parameters:
        - $ref: '#/parameters/query_limit'
        - $ref: '#/parameters/query_id'
        - $ref: '#/parameters/query_name'
        - $ref: '#/parameters/query_fqname'
        - $ref: '#/parameters/query_type'
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfDatsets
            type: array
            items:
              $ref: 'def/dataset.yml'
    post:
      operationId: dataset_api.upload_dataset
      description: add a new dataset
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - $ref: 'def/desc.yml'
        - $ref: '#/parameters/file'
      responses:
        200:
          description: Successful response
          schema:
            $ref: 'def/dataset.yml'
  /.csv:
    get:
      operationId: dataset_api.list_dataset_csv
      description: list all datasets as csv file
      parameters:
        - $ref: '#/parameters/query_limit'
        - $ref: '#/parameters/query_id'
        - $ref: '#/parameters/query_name'
        - $ref: '#/parameters/query_fqname'
        - $ref: '#/parameters/query_type'
        - name: delimiter
          in: query
          required: false
          default: ;
          type: string
      produces:
        - text/csv
      responses:
        200:
          description: Successful response
          schema:
            title: CSV File
            type: file
  /.tree.json:
    get:
      operationId: dataset_api.list_dataset_tree
      description: list all datasets as tree
      parameters:
        - $ref: '#/parameters/query_limit'
        - $ref: '#/parameters/query_id'
        - $ref: '#/parameters/query_name'
        - $ref: '#/parameters/query_fqname'
        - $ref: '#/parameters/query_type'
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/datasetnode'
  /{datasetid}:
    parameters:
      - $ref: 'def/datasetid.yml'
    get:
      operationId: dataset_api.get_dataset
      description: get the data of this dataset
      parameters:
        - $ref: 'def/range.yml'
      responses:
        200:
          description: Successful response
          schema:
            title: dataset object
            type: object
        404:
          $ref: 'def/notFound.yml'
    put:
      operationId: dataset_api.put_dataset
      description: updates this dataset
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - $ref: '#/parameters/desc_optional'
        - $ref: '#/parameters/file'
      responses:
        200:
          description: Successful response
          schema:
            $ref: 'def/dataset.yml'
        400:
          $ref: 'def/invalid.yml'
        500:
          $ref: 'def/error.yml'
    post:
      description: modifies this dataset
      operationId: dataset_api.post_dataset
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - $ref: '#/parameters/desc_optional'
        - $ref: '#/parameters/file'
      responses:
        200:
          description: Successful response
          schema:
            $ref: 'def/dataset.yml'
        400:
          $ref: 'def/invalid.yml'
        404:
          $ref: 'def/notFound.yml'
        500:
          $ref: 'def/error.yml'
    delete:
      description: deletes this dataset
      operationId: dataset_api.delete_dataset
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/dataset_deleted'
        400:
          $ref: 'def/invalid.yml'
        404:
          $ref: 'def/notFound.yml'
  /{datasetid}/desc:
    parameters:
      - $ref: 'def/datasetid.yml'
    get:
      operationId: dataset_api.get_dataset_desc
      description: get the description of this dataset
      responses:
        200:
          description: Successful response
          schema:
            $ref: 'def/dataset.yml'
        404:
          $ref: 'def/notFound.yml'

parameters:
  desc_optional:
    name: desc
    in: formData
    description: dataset desc
    required: false
    type: string
    format: json
  file:
    name: file
    in: formData
    description: uploaded file
    required: false
    type: file
  query_limit:
    name: limit
    in: query
    required: false
    description: limit the number of returned items
    type: integer
    default: -1
  query_type:
    name: type
    in: query
    required: false
    description: filter by type regex
    type: string
    format: regex
  query_name:
    name: name
    in: query
    required: false
    description: filter by name regex
    type: string
    format: regex
  query_fqname:
    name: fqname
    in: query
    required: false
    description: filter by fqname regex
    type: string
    format: regex
  query_id:
    name: id
    in: query
    required: false
    description: filter by id regex
    type: string
    format: regex

definitions:
  dataset_deleted:
    type: object
    description: status info
    properties:
      status:
        type: string
      msg:
        type: string
      id:
        type: string
  datasetnode:
    type: object
    description: a dataset node
    properties:
      name:
        type: string
      data:
        $ref: 'def/dataset.yml'
      children:
        type: array
        items:
          $ref: '#/definitions/datasetnode'
    required:
      - name
