swagger: '2.0'

info:
  version: "0.0.1"
  title: DataSet Graph API

produces:
  - application/json

paths:
  /vector/{datasetid}:
    parameters:
      - $ref: 'def/datasetid.yml'
    get:
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/vector_dataset'
        404:
          $ref: 'def/notFound.yml'
  /vector/{datasetid}/data:
    parameters:
      - $ref: 'def/datasetid.yml'
    get:
      parameters:
        - $ref: 'def/range.yml'
        - name: f_pretty_print
          in: query
          type: boolean
          required: false
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/vector_data'
        404:
          $ref: 'def/notFound.yml'
  /vector/{datasetid}/data.json:
    parameters:
      - $ref: 'def/datasetid.yml'
    get:
      parameters:
        - $ref: 'def/range.yml'
        - name: f_pretty_print
          in: query
          type: boolean
          required: false
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/vector_data'
        404:
          $ref: 'def/notFound.yml'
  /vector/{datasetid}/data.csv:
    parameters:
      - $ref: 'def/datasetid.yml'
    get:
      parameters:
        - $ref: 'def/range.yml'
        - name: f_rows
          in: query
          type: boolean
          required: false
        - name: f_cols
          in: query
          type: boolean
          required: false
        - name: f_delimiter
          in: query
          type: string
          default: ;
          required: false
      produces:
        - text/csv
      responses:
        200:
          description: Successful response
          schema:
            type: file
        404:
          $ref: 'def/notFound.yml'
  /vector/{datasetid}/rows:
    parameters:
      - $ref: 'def/datasetid.yml'
    get:
      parameters:
        - $ref: 'def/range.yml'
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              type: string
        404:
          $ref: 'def/notFound.yml'

  /vector/{datasetid}/rowsIds:
    parameters:
      - $ref: 'def/datasetid.yml'
    get:
      parameters:
        - $ref: 'def/range.yml'
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              type: integer
        404:
          $ref: 'def/notFound.yml'

  /vector/{datasetid}/raw:
    parameters:
      - $ref: 'def/datasetid.yml'
    get:
      parameters:
        - $ref: 'def/range.yml'
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              format: any
              type: string
        404:
          $ref: 'def/notFound.yml'

  /vector/{datasetid}/hist:
    parameters:
      - $ref: 'def/datasetid.yml'
    get:
      parameters:
        - $ref: 'def/range.yml'
        - name: bins
          in: query
          required: false
          type: integer
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              type: integer
        404:
          $ref: 'def/notFound.yml'

definitions:
  vector_dataset:
    type: object
    description: a vector dataset
    allOf:
      - $ref: 'def/dataset.yml'
      - type: object
        required:
          - size
          - value
          - idtype
        properties:
          idtype:
            type: string
          size:
            type: integer
          value:
            $ref: 'def/valuetype.yml'
  vector_data:
    type: object
    description: vector as json
    properties:
      data:
        type: array
        items:
          format: any
          type: string
      rows:
        type: array
        items:
          type: string
      rowIds:
        type: array
        items:
          type: integer
    required:
      - data
      - rows
      - rowIds
responses:
  success_desc:
    description: Successful response
    schema:
      $ref: '#/definitions/vector_dataset'
