swagger: '2.0'

# This is your document metadata
info:
  version: '0.0.1'
  title: Dataset API

produces:
  - application/json

paths:
  /:
    get:
      x-swagger-router-controller: phovea_server
      operationId: dataset_api.list_dataset
      description: list all datasets
      parameters:
        - $ref: '#/parameters/query_limit'
        - $ref: '#/parameters/query_id'
        - $ref: '#/parameters/query_name'
        - $ref: '#/parameters/query_fqname'
        - $ref: '#/parameters/query_type'
      responses:
        '200':
          description: Successful response
          schema:
            title: ArrayOfDatsets
            type: array
            items:
              $ref: '#/definitions/dataset'
    post:
      x-swagger-router-controller: phovea_server
      operationId: dataset_api.upload_dataset
      description: add a new dataset
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - $ref: '#/parameters/desc'
        - $ref: '#/parameters/file'
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/dataset'
  /.csv:
    get:
      x-swagger-router-controller: phovea_server
      operationId: dataset_api.list_dataset_csv
      description: list all datasets as csv file
      parameters:
        - $ref: '#/parameters/query_limit'
        - $ref: '#/parameters/query_id'
        - $ref: '#/parameters/query_name'
        - $ref: '#/parameters/query_fqname'
        - $ref: '#/parameters/query_type'
        - name: delimiter
          in: query
          required: false
          default: ;
          type: string
      produces:
        - text/csv
      responses:
        '200':
          description: Successful response
          schema:
            title: CSV File
            type: string
  /.tree.json:
    get:
      x-swagger-router-controller: phovea_server
      operationId: dataset_api.list_dataset_tree
      description: list all datasets as tree
      parameters:
        - $ref: '#/parameters/query_limit'
        - $ref: '#/parameters/query_id'
        - $ref: '#/parameters/query_name'
        - $ref: '#/parameters/query_fqname'
        - $ref: '#/parameters/query_type'
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/datasetnode'
  /{datasetid}:
    parameters:
      - $ref: '#/parameters/datasetid'
    get:
      x-swagger-router-controller: phovea_server
      operationId: dataset_api.get_dataset
      description: get the data of this dataset
      parameters:
        - $ref: '#/parameters/range'
      responses:
        '200':
          description: Successful response
          schema:
            title: dataset object
            type: object
        '404':
          $ref: '#/responses/notFound'
    put:
      x-swagger-router-controller: phovea_server
      operationId: dataset_api.put_dataset
      description: updates this dataset
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - $ref: '#/parameters/desc_optional'
        - $ref: '#/parameters/file'
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/dataset'
        '400':
          $ref: '#/responses/invalid'
        '500':
          $ref: '#/responses/error'
    post:
      description: modifies this dataset
      x-swagger-router-controller: phovea_server
      operationId: dataset_api.post_dataset
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - $ref: '#/parameters/desc_optional'
        - $ref: '#/parameters/file'
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/dataset'
        '400':
          $ref: '#/responses/invalid'
        '404':
          $ref: '#/responses/notFound'
        '500':
          $ref: '#/responses/error'
    delete:
      description: deletes this dataset
      x-swagger-router-controller: phovea_server
      operationId: dataset_api.delete_dataset
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/dataset_deleted'
        '400':
          $ref: '#/responses/invalid'
        '404':
          $ref: '#/responses/notFound'
  /{datasetid}/desc:
    parameters:
      - $ref: '#/parameters/datasetid'
    get:
      x-swagger-router-controller: phovea_server
      operationId: dataset_api.get_dataset_desc
      description: get the description of this dataset
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/dataset'
        '404':
          $ref: '#/responses/notFound'

parameters:
  datasetid:
    name: datasetid
    in: path
    description: dataset id
    required: true
    type: string
  desc:
    name: desc
    in: formData
    description: dataset desc
    required: true
    type: string
    format: json
  desc_optional:
    name: desc
    in: formData
    description: dataset desc
    required: false
    type: string
    format: json
  range:
    name: range
    in: query
    description: range to subset
    required: false
    type: string
    format: range
  file:
    name: file
    in: formData
    description: uploaded file
    required: false
    type: file
  query_limit:
    name: limit
    in: query
    required: false
    description: limit the number of returned items
    type: integer
    default: -1
  query_type:
    name: type
    in: query
    required: false
    description: filter by type regex
    type: string
    format: regex
  query_name:
    name: name
    in: query
    required: false
    description: filter by name regex
    type: string
    format: regex
  query_fqname:
    name: fqname
    in: query
    required: false
    description: filter by fqname regex
    type: string
    format: regex
  query_id:
    name: id
    in: query
    required: false
    description: filter by id regex
    type: string
    format: regex

definitions:
  dataset:
    type: object
    description: a dataset definition
    required:
      - id
      - name
      - fqname
      - type
    properties:
      id:
        type: string
      name:
        type: string
      fqname:
        type: string
      type:
        type: string
      creator:
        type: string
      ts:
        type: number
  dataset_deleted:
    type: object
    description: status info
    properties:
      status:
        type: string
      msg:
        type: string
      id:
        type: string
  datasetnode:
    type: object
    description: a dataset node
    properties:
      name:
        type: string
      data:
        $ref: '#/definitions/dataset'
      children:
        type: array
        items:
          $ref: '#/definitions/datasetnode'
    required:
      - name

responses:
  error:
    description: Internal Server Error
    schema:
      title: Error
      type: string
  invalid:
    description: Invalid Request
    schema:
      title: Error
      type: string
  notFound:
    description: Not Found
    schema:
      title: Error
      type: string
