swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.1"
  title: IDType API

produces:
  - application/json

# Describe your paths here
paths:
  /:
    get:
      operationId: idtype_api.list_idtypes
      description: list all idtypes
      responses:
        '200':
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: ArrayOfIDTypes
            type: array
            items:
              $ref: '#/definitions/idtype'
  /{idtype}/map:
    parameters:
      - $ref: '#/parameters/idtype'
    get:
      operationId: idtype_api.get_map
      description: returns the uids for the given id names
      parameters:
        - $ref: '#/parameters/idnames'
      responses:
        '200':
          description: Successful response
          schema:
            title: ArrayOfUIDs
            type: array
            items:
              type: integer
  /{idtype}/map/{idname}:
    parameters:
      - $ref: '#/parameters/idtype'
      - $ref: '#/parameters/idname'
    get:
      operationId: idtype_api.get_map_single
      description: returns the uid for the given id name
      responses:
        '200':
          description: Successful response
          schema:
            title: ID name
            type: string
  /{idtype}/unmap:
    parameters:
      - $ref: '#/parameters/idtype'
    get:
      operationId: idtype_api.get_unmap
      description: returns the id names for the given uids
      parameters:
        - $ref: '#/parameters/idnames'
      responses:
        '200':
          description: Successful response
          schema:
            title: ArrayOfIDNames
            type: array
            items:
              type: string
  /{idtype}/unmap/{uid}:
    parameters:
      - $ref: '#/parameters/idtype'
      - $ref: '#/parameters/uid'
    get:
      operationId: idtype_api.get_unmap_single
      description: returns the id name for the given uid
      responses:
        '200':
          description: Successful response
          schema:
            title: ID Name
            type: string
  /{idtype}/:
    parameters:
      - $ref: '#/parameters/idtype'
    get:
      operationId: idtype_api.get_maps_to
      description: returns a list of all mapable types, i.e. that ar possible target idtypes
      responses:
        '200':
          description: Successful response
          schema:
            title: ArrayOfIDTypesIDs
            type: array
            items:
              type: string
  /{source}/{target}:
    parameters:
      - $ref: '#/parameters/source'
      - $ref: '#/parameters/target'
    get:
      operationId: idtype_api.get_convert
      description: maps between given source idtype to the target idtype returning the id names of the target idtype
      parameters:
        - $ref: '#/parameters/uids'
        - $ref: '#/parameters/q'
        - $ref: '#/parameters/mode'
      responses:
        '200':
          description: Successful response
          schema:
            title: ArrayOfIDNames
            type: array
            items:
              type: string
        400:
          description: Invalid arguments
  /{source}/{target}/{uid}:
    parameters:
      - $ref: '#/parameters/source'
      - $ref: '#/parameters/target'
      - $ref: '#/parameters/uid'
    get:
      operationId: idtype_api.get_convert_single
      description: maps between given source idtype uid to the target idtype returning the id name of the target idtype
      parameters:
        - $ref: '#/parameters/mode'
      responses:
        # Response code
        '200':
          description: Successful response
          # Use JSON Schema format
          schema:
            title: IDName
            type: string
  /{source}/{target}/map:
    parameters:
      - $ref: '#/parameters/source'
      - $ref: '#/parameters/target'
    get:
      operationId: idtype_api.get_convert_id
      description: maps is between given ssource idtype to the target idtype returning the id names of the target idtype
      parameters:
        - $ref: '#/parameters/uids'
        - $ref: '#/parameters/q'
        - $ref: '#/parameters/mode'
      responses:
        # Response code
        '200':
          description: Successful response
          schema:
            title: ArrayOfUIDs
            type: array
            items:
              type: integer
        400:
          description: Invalid arguments
  /{source}/{target}/map/{idname}:
    parameters:
      - $ref: '#/parameters/source'
      - $ref: '#/parameters/target'
      - $ref: '#/parameters/idname'
    get:
      operationId: idtype_api.get_convert_id_single
      description: maps is between given ssource idtype to the target idtype returning the id names of the target idtype
      parameters:
        - $ref: '#/parameters/mode'
      responses:
        '200':
          description: Successful response
          schema:
            title: UID
            type: integer


parameters:
  source:
    name: source
    in: path
    description: source idtype
    required: true
    type: string
  target:
    name: target
    in: path
    description: target idtype
    required: true
    type: string
  idtype:
    name: idtype
    in: path
    description: idtype
    required: true
    type: string
  idname:
    name: idname
    in: path
    description: source id name
    required: true
    type: integer
  idnames:
    name: idnames
    in: query
    description: source id names
    required: true
    type: array
    items:
      type: string
    collectionFormat: multi
  uid:
    name: uid
    in: path
    description: source uid
    required: true
    type: integer
  uids:
    name: uids
    in: query
    description: source uids as range string
    required: false
    type: string
    format: range
  mode:
    name: mode
    in: query
    description: 'in case of multi mapping should all(default) or just the first one returned. options: all|single'
    required: false
    type: string
    default: all
  q:
    name: q
    in: query
    description: source uids separated by ,
    required: false
    type: array
    items:
      type: string
    collectionFormat: csv

definitions:
  idtype:
    type: object
    description: an IDType
    required:
      - id
      - name
      - names
    properties:
      id:
        type: string
      name:
        type: string
      names:
        type: string

