swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.1"
  title: Last Deployment API

produces:
  - application/json

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /:
    # This is a HTTP operation
    get:
      x-swagger-router-controller: phovea_server
      operationId: last_deployment.get_last_deployment
      # Describe this verb here. Note: you can use markdown
      description: |
        returns the last deployment timestamp
      responses:
        # Response code
        '200':
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: Timestamp as string
            type: object
            properties:
              timestamp:
                type: string
                format: date-time
